version: '2.3.3'

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MySecurityApp
      - FLASK_DEBUG=1
    expose:
      - 8000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"